[build]
  command = "yarn build"
  publish = "_site"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Vary= "Accept-Encoding"

[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Vary= "Accept-Encoding"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/*.jsonld"
  [headers.values]
    Content-Type = "application/ld+json; charset=utf-8"

[[headers]]
  for = "/*.jrd"
  [headers.values]
    Content-Type = "application/jrd+json; charset=utf-8"

[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"

# Favicon
[[redirects]]
  from = "/favicon.ico"
  to = "/static/img/favicon/favicon.ico"
  status = 200
  force = true

# Netlify subdomain
[[redirects]]
  from = "https://bejoistic.netlify.com/*"
  to = "https://bejoistic.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://bejoistic.netlify.app/*"
  to = "https://bejoistic.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.bejoistic.com/*"
  to = "https://bejoistic.com/:splat"
  status = 301
  force = true

# More miscellaneous mirrors/redirects:
[[redirects]]
  from = "*"
  to = "/404"
  status = 404
[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 302
  force = true
[[redirects]]
  from = "/pubkey"
  to = "https://keybase.io/bejoisticom/pgp_keys.asc"
  status = 302
  force = true

# H A C K E R M A N ( ͡° ͜ʖ ͡°)
[[redirects]]
  from = "*/wp-admin/*"
  to = "/403.html"
  status = 403
[[redirects]]
  from = "*/admin/*"
  to = "/403.html"
  status = 403
[[redirects]]
  from = "*/wp-login.php"
  to = "/403.html"
  status = 403
[[redirects]]
  from = "*/login.php"
  to = "/403.html"
  status = 403
[[redirects]]
  from = "*/wlwmanifest.xml"
  to = "/403.html"
  status = 403
